language: node_js
cache:
  directories:
    - node_modules
node_js:
  - lts/*

install:
  - npm install
  - npm install codecov -g

script:
  - npm run test # 执行测试脚本

after_success:
  - codecov -f coverage/*.json # 推送代码覆盖度

deploy:
  provider: npm
  email: '1461304646@qq.com'
  api_key:
    secure: BPoWM7PQcQx/9lAAtELhwkbv22KvyblgqoR6JtR7oGGI6HNdlsEKU4qCyTVnClA1JlQAS7CwAzVywcfc6LXNdbGXE6uvJzH2K7NDAIvAnrlIzMI2t2dRQXjxq9iuWMKWUfEYQBErLLDyZBfuVOJ30Ch4v9+wAwOreak1u8xvnCuO8RmZe3RpMrAebvlwHz9brZ2R//gGwAsvl8VH5BmuhNWf3g4w1cwkw7iPlTxZdsRq7U6OvNpCy/zV70Kz4E7apbdQNZGEakZRhUWLaruBHMyVxQma3RCfo+kPTdug/5dULtUOlCEGYc3Z/HU6SLum2Q8hmRKQj1MPfpw+g4ANEO1W340XYfxZoBmsh0tnJ+V1QhxzyMdjpbXtblhpb6xlvxKonxW/lubVvmcFDtLBeZa64dBcTupLa82m93MS6A0nqF77NQJ6ddVEZNOlrbNiQ5oced9bhSjeWlNUvQZaGjRc5qHje6enOhnhn030LEoA9/K0Dw2PCNXdo19wmnP9ZSESSjhTqKSrp66+S6O6hA14chROyZYoEcirn+cV3btWeOimcLG6TL9hLoEqkzp6xVB99o2HVoiqgjTGKYI8BkPETw7PpN4dIbKYXicko67TqB9EyAg2ac/hs78ZbHzk6M0jhnPGvYJz6fUEN9HJoz4aS4ymN6ExYa4PL0t+x8U=
  on:
    tags: true
    branch: master
    repo: unity-template/utils
  tag: latest
  skip_cleanup: 'true'
  condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
