language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: 1461304646@qq.com
  api_key:
    secure: a4Cc2iPzm1N3OYF1oaAA1E5CS23LDlqOLzgqw99wQ6Stg54PL/cQWkutt/gBxAsgvxQX3xT3MTeUz7Pg0GtTi66cQhtZckK61wn0kOFNM4faLuabLvnVdMlU2lxnlX1FOkZFAkavn2k/gTKnYE4zkMF3LzMDZUWNoemAYXOD8Ersb7mlXYCXvwwpXFDRTFh1bu2vv34UaQun2WzSyjpK42OwpIV5RSNRYpsfuq1DX8N9kHEwblpYS7l+m3BYTLuI7y28/92C/h+e+I80E7XbmnJrFmmqti6AiQtFpr45uqYv3qBiNDcug0KWwjdL22ML48YyW3py7uizb/wEwPlf953Z5ITb2UTuAVwulYoSL2F15Q2asskYAOZI9L0s904DbtgxlMSpNtoYttf6hzwCCJ3csTgXPr61th9E5zfSFNOsHeeHxpQioRd5d5ehDJqC/5a6cA34qm1eaJxOj5LL1LWtIfrve8CrP224Ns63HY2EBWj5Ga/BAOvL9hs2AxL+s9FjJvlYrPF6KJ0HGDd3Ec0JR40yd0zViluqW9dP6g4RCxcdvycGgIQWUxB9QCI1VIZPU7Fp5oEV3E2FjO206slLLramxGCYtgCcPm0LWG0j1bTOI69ujvHnIX9Z6WJSZTV8V4XNJd9rWJypo9QMctI0v5/FEaqefj9xBXv8sJo=
  on:
    tags: true
    branch: master
  tag: latest
  skip-cleanup: true
  condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
