language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: isgenluo@gmail.com
  api_key:
    secure: jMGQkvnurpxVWm3dWHSUb9Ac/qo6MD5hlOrCN83/J8yHkTfBjoA3mOnhiaqGc+Yjao2y3tINWTB7Uvt8l5xKVLamvPyYyyH1qk2bbTFn1nKjCc1TIg+UfsQZBS2jr3/AyM2vWEgW8Df+E+bWckJclPg9eU6C5GvFGVfNUK3Rn+/T4miMGgQpWE/EP3eu0kb43TpMewBf4Qou1rUZcZa2tNWNEkaZPMybDqZI9tR44i28pdVEMb/cRdjqMu9ayVDBF1duaI7CKU+8vVDZ2WlJFJMD4TW27wCtBV+g1pWZ/FKrISIHy1P+1txNUUSmSe5JQhfiYZimMyF45Zl5M2nqoi4EU7Syb51BNyHk/MJAuJhwDo/DwLKPAPBquEHoeMxKHOVgCK7mvpJYSYFyHpAnIlRUO4/rBGEzbniWZCg5H07LU5WNipe580KsZBm+0CDwcLrEZzQcagGB5izXD6DxlIe4J2BNoYDfPlIKQV15hCgk+Np95BckiYZd8Lu0CEJad/Cgs0TSEv5qcAVca9eK8IWY/V5Qvm8yhw4VSRnwmnO2cFdNDyFtrgrF67CcQx9e0hMZr60G8ASEihuLUV9+fH93gWZBLdbGWpPqbI9dN1/SN7KnYfTmi8HZModBleQNvSNhIACLQ5oabxGAs7iKLtvKOYViUdt8+7q12VdGSKs=
  on:
    tags: true
    branch: master
  tag: latest
  skip-cleanup: true
  condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
