language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
- npm install codecov -g
script:
- npm run test
after_success:
- codecov -f coverage/*.json

before_deploy:
- npm run checkVersion # 版本发布前首先验证版本
- git config --local user.name "Genluo"
- git config --local user.email "isgenluo@gmail.com"

deploy:
  - provider: npm # 包发布部署
    email: 1461304646@qq.com
    api_key:
      secure: UxtjRjrUN2Oy3EhLrXFgtAkxcNAwCotevuV3xU1rEymDVFySs9EvoVomWWJZo0s04nVe/HxUvNeRXsC9d7v5TjroUv4yUnFCW1HgWKM/HQ/XYWTQcYBUr8r602s4W90CAOFgE4CVt8uguwBAsoy2zUanDdc/hhGww+jxwDLbXFnyxg7m6BqlISGVbl301wTwoPYyr46C/3KGiJ20INXwJ0qmnC0I0LEOO7wloVIrKad3PPgUEky/cqea4tViIqK+9URrXgmv72PyhGoMTh1ACTZaMuzb4GJw+bNTwU6wHNGRoeEDEQnkfKlWyVInmEnWr3HvENr/od2PuTLW9a0rGAGoMEegTp68GqiLrHJUuzT6TgqX6qa71D/TlKJAkEDnOsFuXdHCH2DjGEhGRgtt/bXFr8W7rLMTnBDkYyw0zhM8J5i1LtLSzxbdaRD0kOp42W0ShdmwhPzNBtCh2ulPbwdRXb0A/XoVszEi21s7FUV4w5TfYTdkh5Ty3Rim6mXF5CjCrwbDLTVUd+IR2B08eUnjRpc6ZZmLIqy3UCPmnjJUZ4I54WaoZ/ooFasqK/7Ka9gKJPxw655n9WDiV37+ensl3SYMWdSeHRIt3AFd4zDaJUch1mOTwPpfD9UoelFJX3vh17QFuUnIkdQwyKtBpab2JLKKZAdKF8POGXyCmoQ=
    on:
      tags: true
    cleanup: 'true'
  - provider: pages # API文档部署
    skip_cleanup: true
    github_token:
      secure: Hrz9TVst+cl3bLKxkSfWfOXd+LJLok1gTGHKoSxvOEUSN55rhnqftiBu9OVywi5y3yxyO3pr3BgADOq7JToW1i+biF5XRO9Ijab1WghCW/B31nClasUUhEedn1v7tkKYVwXHpxoBE9RsL1ESyAffnrd7Usa3OtKmOb/6QznUIaJVuMcV5r4g1tP6Dt4UOMu3kPxQIisE0o40zsFXKAvlHDwuENF4T58QfYKEmbwunW1nhLGWoaSGDudhfeourGqRO34g1p5B0q6KT8uRwtt4Bo2aeOdrpiIYFtW0xLB4xmzZW/KlpxEoiu5fq1O5+JDqhDjOSixK+uNoSMjgJF07gs12ylypmjo8byk8Hg78vt2hMJ8hhbywJnxd0ECwewKDd9knHCw7LKJf1kdICza2PiQbLkfjWtyl7TAheU+ex/bEy+xxt1/6QA5z9Ykstd/4akkPWDWeWUackrQMpRtnJ8QXlh/beAqVaGm2mpfjndx9bZMv9AkooWOH7wjvXvdQr1nbDJ9w+T9YMseIlh+MqAe+wavbTVIygz/1OAhM6TEx/gdMvK6vgoB33MZ0i2Diqogcna9e31yCYzibU9A8oNJjpCaY42xEszLVX9gXaIDCU/xYXlChJhpL1zkuG17DrBUIiABJuV9olOlVVP7fvO9PNxjXEqT1PtdznA7QKso=
    local_dir: docs
    keep_history: true
    on:
      branch: master
