language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
- npm install codecov -g
script:
- npm run test
after_success:
- codecov -f coverage/*.json
deploy:
  provider: npm
  email: 1461304646@qq.com
  api_key:
    secure: JPYW1wsEl1gqi68sOcBe0fZAfRovpp4B0uPzWoA+aehRtbf2i8/O056iSvsAhdkdjSKKK3MqlrkrZ9MYPZuNcr7tL+2+W2NbTgxbE9XsrVmWyoAkeDT52bltikhOnzoFvypO4jtRx+u8RlVq/2URjQmTH34dNaJijv2FKcUFEji6zJQzKSEQJsoBjkm9xisHey58lOSzSbXyMVO9zgxubBCLNlTslbn5+ZPWpNtiQRSOaHxhNt89lLGUlbvGCMadtxEasNhh/u45UD8a/Ph62u2fuiNXlTfcov/Px/rxR3wym7rztjWCKu9k5fuRfOxu34OKxiT7O+TVoIqGHC74wJWqFlF1+iwk41RVIMa1n9s3SZNcGGO9wrlUFETTlP8Cy8nUe+tLa6FgeYy8yqoxw8/OJEKUqyzfG/DjCBB3B7dbCon9IdFxhnS1bJeQhewdHciyOikuia6W4Pa9YH/uvwJmlRe3XMuaWWapCb1YI8gROedcrNfVkEXH4E/mjzkGtuASkmij6Naj7Msrdo7cLrNsa4QSyI/pzDMm3sN9bdft93RL8Zvj0SA9lckr6PhjJ+9Q4dsFvQdDSqyjIKLHZB/svIXAshAoFlLRPE6vER0OxN6dnOyRJNq8XPB6jU3aJllLy5VsZEcKQUKetiD8pUJTxldyE9PG9Z7iYKn01Wk=
  on:
    tags: true
    branch: master
    repo: unity-template/utils
  tag: latest
  skip_cleanup: 'true'
  condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
