# This is a basic workflow to help you get started with Actions

name: onex-utils-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
      - uses: actions/checkout@master

      - name: Generate coverage report ⏳
        run: |
          npm install
          npm install codecov -g
          npm run test
          codecov -f coverage/*.json

      - name: Deploy codecov 🚀
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout 🛎️
    - uses: actions/checkout@master

    - name: Generate build file 🧬
      run: |
        npm install
        npm run build
        npm run tsdoc

    - name: Deploy docs 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
    
    - name: Deploy npm 🚀
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    
