# This is a basic workflow to help you get started with Actions

name: onex-utils-test

# Controls when the workflow will run
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Generate coverage report ⏳
        run: |
          npm install
          npm run test

      - name: Send email
        # tells the Github Actions to always run this step
        # regardless of whether the preceding steps have been
        # executed successfully or not
        if: always() 
        uses: devellany/send-mailer@master
        with:
          host: smtp.google.com
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_ADDRESS}}
          to: lg208143@alibaba-inc.com
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # Optional content type (defaults to text/plain)
          contentType: text/plain

