# This is a basic workflow to help you get started with Actions

name: onex-utils-test

# Controls when the workflow will run
on:
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Run Test ⏳
        run: |
          npm install
          npm run test