# This is a basic workflow to help you get started with Actions

name: onex-utils-test

# Controls when the workflow will run
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Generate coverage report ⏳
        run: |
          npm install
          npm install codecov -g
          npm run test
          codecov -f coverage/*.json

      - name: Deploy codecov 🚀
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
